version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./main:/home
    networks:
      - N1
    container_name: py_container
    image: py_image
    restart: on-failure
    command: ["sleep","infinity"]
  

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'dhruv'
      MYSQL_PASSWORD: 'dhruv'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3001:3306"
    volumes:
      - t1:/var/lib/mysql
    networks:
      - N1
    container_name: mysql_container

volumes:
  t1: 
networks:
  N1:
